In [1]:
import numpy as np

# 1. Create the dataset
# Points: (2,0), (0,2), (-2,-2)
X = np.array([
    [ 2,  0],
    [ 0,  2],
    [-2, -2]
], dtype=float)

print("Original data matrix X (rows = samples):")
print(X)
print("-" * 50)

# 2. Compute the mean of each feature (column-wise)
mean_vec = X.mean(axis=0)
print("Mean of each feature:")
print(mean_vec)
print("-" * 50)

# 3. Center the data: X_centered = X - mean
X_centered = X - mean_vec
print("Centered data X_centered (X - mean):")
print(X_centered)
print("-" * 50)

# 4. Compute covariance matrix (two ways)
n_samples = X.shape[0]
denom = n_samples - 1  # n - 1

# 4a. Classical manual formula
x = X_centered[:, 0]
y = X_centered[:, 1]

var_x = np.sum(x ** 2) / denom
var_y = np.sum(y ** 2) / denom
cov_xy = np.sum(x * y) / denom

C_manual = np.array([
    [var_x,  cov_xy],
    [cov_xy, var_y ]
])

print("Covariance matrix (manual formulas):")
print(C_manual)
print("-" * 50)

# 4b. Matrix formula: C = 1/(n-1) * X_centered^T X_centered
C_matrix = (X_centered.T @ X_centered) / denom
print("Covariance matrix (matrix formula):")
print(C_matrix)
print("-" * 50)

# They should be identical:
print("Are both covariance matrices equal? ->", np.allclose(C_manual, C_matrix))
print("-" * 50)

C = C_matrix  # Use this as our covariance matrix

# 5. Eigen-decomposition of covariance matrix
eigvals, eigvecs = np.linalg.eig(C)

print("Eigenvalues (unsorted):")
print(eigvals)
print("\nEigenvectors (columns, unsorted):")
print(eigvecs)
print("-" * 50)

# 6. Sort eigenvalues and eigenvectors (descending eigenvalues)
idx = np.argsort(eigvals)[::-1]  # indices for sorted eigenvalues (largest first)
eigvals_sorted = eigvals[idx]
eigvecs_sorted = eigvecs[:, idx]

print("Eigenvalues (sorted, largest to smallest):")
print(eigvals_sorted)
print("\nEigenvectors (columns, sorted to match eigenvalues):")
print(eigvecs_sorted)
print("-" * 50)

# 7. Explained variance ratios
total_var = np.sum(eigvals_sorted)
explained_var_ratio = eigvals_sorted / total_var

print("Total variance (trace of C):", total_var)
print("Explained variance ratio (per principal component):")
print(explained_var_ratio)
print("-" * 50)

# 8. PCA transformation matrix (columns = principal directions)
Q = eigvecs_sorted  # 2x2 matrix, PC1 in col 0, PC2 in col 1
print("PCA transformation matrix Q (columns = PC directions):")
print(Q)
print("-" * 50)

# 9. Project centered data into PCA space: Z = X_centered @ Q
Z = X_centered @ Q
print("Data in PCA coordinates Z = X_centered @ Q:")
print(Z)
print("-" * 50)

# 10. Verify variance along PCs matches eigenvalues
# Var(PC1) = eigenvalue_1, Var(PC2) = eigenvalue_2
pc1 = Z[:, 0]
pc2 = Z[:, 1]

var_pc1 = np.sum(pc1 ** 2) / denom
var_pc2 = np.sum(pc2 ** 2) / denom

print("Variance along PC1 (from projected data):", var_pc1)
print("Variance along PC2 (from projected data):", var_pc2)
print("These should match eigenvalues:", eigvals_sorted)
print("-" * 50)

# 11. (Optional) Reconstruct data from PCA coordinates
# X_recon = Z @ Q^T + mean_vec
X_reconstructed = Z @ Q.T + mean_vec

print("Reconstructed data from PCA (should equal original X):")
print(X_reconstructed)
print("Reconstruction error ||X - X_reconstructed||:")
print(np.linalg.norm(X - X_reconstructed))
print("-" * 50)


Original data matrix X (rows = samples):
[[ 2.  0.]
 [ 0.  2.]
 [-2. -2.]]
--------------------------------------------------
Mean of each feature:
[0. 0.]
--------------------------------------------------
Centered data X_centered (X - mean):
[[ 2.  0.]
 [ 0.  2.]
 [-2. -2.]]
--------------------------------------------------
Covariance matrix (manual formulas):
[[4. 2.]
 [2. 4.]]
--------------------------------------------------
Covariance matrix (matrix formula):
[[4. 2.]
 [2. 4.]]
--------------------------------------------------
Are both covariance matrices equal? -> True
--------------------------------------------------
Eigenvalues (unsorted):
[6. 2.]

Eigenvectors (columns, unsorted):
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
--------------------------------------------------
Eigenvalues (sorted, largest to smallest):
[6. 2.]

Eigenvectors (columns, sorted to match eigenvalues):
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
------------------------------