In [1]:
import numpy as np

In [7]:
zero_d = np.array(3)

In [9]:
zero_d

array(3)

In [11]:
zero_d.ndim

0

In [15]:
zero_d.shape

()

In [17]:
zero_d.size

1

In [19]:
one_d = np.array([1,2,6,7])

In [21]:
one_d

array([1, 2, 6, 7])

In [25]:
one_d.ndim

1

In [23]:
one_d.shape

(4,)

In [27]:
one_d.size

4

In [29]:
two_d = np.array([[1,2,6,7],[6,8,7,9]])

In [31]:
two_d

array([[1, 2, 6, 7],
       [6, 8, 7, 9]])

In [33]:
two_d.ndim

2

In [35]:
two_d.shape

(2, 4)

In [37]:
two_d.size

8

In [67]:
three_d = np.array([[[1,2,6,7],[6,8,7,9]],[[8,9,5,4],[5,5,5,5]],[[9,9,9,9],[6,8,7,9]],[[1,2,6,7],[6,8,7,9]]])

In [69]:
three_d

array([[[1, 2, 6, 7],
        [6, 8, 7, 9]],

       [[8, 9, 5, 4],
        [5, 5, 5, 5]],

       [[9, 9, 9, 9],
        [6, 8, 7, 9]],

       [[1, 2, 6, 7],
        [6, 8, 7, 9]]])

In [61]:
three_d.ndim

3

In [63]:
three_d.shape

(4, 2, 4)

In [65]:
three_d.size

32

In [51]:
four_d=np.array([[[[1,2,6,7],[6,8,7,9]],[[8,9,5,4],[5,5,5,5]],[[9,9,9,9],[6,8,7,9]]],[[[1,2,6,7],[1,8,4,9]],[[8,9,5,4],[5,5,5,5]],[[1,1,1,1],[6,8,7,9]]]])

In [53]:
four_d.ndim

4

In [55]:
four_d.shape

(2, 3, 2, 4)

In [57]:
four_d.size

48