In [64]:
import numpy as np
import pandas as pd
import time

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC, SVC
from sklearn.metrics import accuracy_score,confusion_matrix

In [3]:
df=pd.read_csv(r"C:\Users\91861\Desktop\Artifical Intelligence\Machine Leraning\10. SVM\Churn_Modelling.csv")

In [4]:
# Drop ID-like columns
df = df.drop(columns=["RowNumber", "CustomerId", "Surname"])

# Target
y = df["Exited"].values
X = df.drop(columns=["Exited"])

# One-hot encode categoricals
X = pd.get_dummies(
    X,
    columns=["Geography", "Gender"],
    drop_first=True
)

# Convert labels {0,1} → {-1,+1}
y = np.where(y == 0, -1, 1)




In [5]:
X.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Geography_Germany  Geography_Spain  \
0               1        101348.88              False            False   
1               1        112542.58              False             True   
2               0        113931.57              False            False   
3               0         93826.63              False            False   
4               1         79084.10              False             True   

   Gender_Male  
0        False  
1        False  
2        False  
3        False  
4        False

In [6]:
y

array([ 1, -1,  1, ...,  1,  1, -1])

In [7]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X.values, y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

# Standardize
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

In [8]:
start = time.time()
lin_svm = LinearSVC(max_iter=5000)
lin_svm.fit(X_train, y_train)
svm_lin_time = time.time() - start
y_pred_lin_svm=lin_svm.predict(X_test)
acc_svm_lin = accuracy_score(y_test, lin_svm.predict(X_test))


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\svm\_classes.py:31: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(


In [9]:
svm_lin_time

0.3135838508605957

In [10]:
acc_svm_lin

0.8104

In [11]:
confusion_matrix(y_test,y_pred_lin_svm)

array([[1953,   38],
       [ 436,   73]], dtype=int64)

In [50]:
#------------------------------------------------------

In [13]:
start = time.time()
linear_svm = SVC(kernel="linear")
linear_svm.fit(X_train, y_train)
svm_linear_time = time.time() - start
y_pred_linear_svm=linear_svm.predict(X_test)
acc_svm_linear = accuracy_score(y_test, linear_svm.predict(X_test))


In [14]:
svm_linear_time

1.6298942565917969

In [15]:
acc_svm_linear

0.7964

In [16]:
confusion_matrix(y_test,y_pred_linear_svm)

array([[1991,    0],
       [ 509,    0]], dtype=int64)

In [52]:
#----------------------------------------------------

In [42]:
start = time.time()
rbf_svm = SVC(kernel="rbf", gamma="scale")
rbf_svm.fit(X_train, y_train)
svm_rbf_time = time.time() - start
y_pred_rbf_svm=rbf_svm.predict(X_test)
acc_svm_rbf = accuracy_score(y_test, rbf_svm.predict(X_test))


In [43]:
svm_rbf_time

1.7350425720214844

In [44]:
acc_svm_rbf

0.8624

In [48]:
confusion_matrix(y_test,y_pred_rbf_svm)

array([[1953,   38],
       [ 306,  203]], dtype=int64)

In [54]:
#--------------------------------------------------

In [56]:
start = time.time()
poly_svm = SVC(kernel="poly", gamma="scale")
poly_svm.fit(X_train, y_train)
svm_poly_time = time.time() - start
y_pred_poly_svm=poly_svm.predict(X_test)
acc_svm_poly = accuracy_score(y_test, poly_svm.predict(X_test))


In [58]:
svm_poly_time

1.8645727634429932

In [60]:
acc_svm_poly

0.8576

In [62]:
confusion_matrix(y_test,y_pred_poly_svm)

array([[1962,   29],
       [ 327,  182]], dtype=int64)